
<html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja">
<head>
<meta charset="UTF-8" />
<title>【練習】OpenLayers マーカーの使い方</title>
<style type="text/css">
#mapdiv .olControlAttribution {
    font-size:13px;
    bottom:3px;
}
#mapdiv { height: 500px; }
</style>

<!--実験用-->
<!--
    <style type="text/css">
        .white-popup {
          position: relative;
          background: #FFF;
          padding: 20px;
          width: auto;
          max-width: 500px;
          margin: 20px auto;
        }
    </style>
    <link rel="stylesheet" href="/css/magnific-popup.css"> 
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> 
    <script src="/js/jquery.magnific-popup.js"></script>    
-->
<!--実験用-->


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3020819-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
	<h1>クリックした位置にマーカーを移動します</h1>

<div id="mapdiv"></div>
<script src="http://www.openlayers.org/api/OpenLayers.js"></script>
  <script>
    var map = new OpenLayers.Map("mapdiv");
    map.addLayer(new OpenLayers.Layer.OSM());
 
	//var lonLat = new OpenLayers.LonLat( 138.38884, 34.97171 )
	var lonLat = new OpenLayers.LonLat( 138.731388, 35.362222 )
          .transform(
            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
            map.getProjectionObject() // to Spherical Mercator Projection
          );

	var zoom = 15;
    map.setCenter (lonLat, zoom);

    var markers = new OpenLayers.Layer.Markers( "Markers" );
    var marker = new OpenLayers.Marker(lonLat) ;
    markers.addMarker(marker);
    map.addLayer(markers);
	
    map.events.register("click", map , function(e){
		//実験用
		//var lonlat = map.getLonLatFromViewPortPx(e.xy);
        ///lonlat.transform(projection3857, projection4326);
        //$("#lat").val(lonlat.lat);
        //$("#lon").val(lonlat.lon);
		//実験用
		
        var opx = map.getLayerPxFromViewPortPx(e.xy) ;
        marker.map = map ;
        marker.moveTo(opx);

		//alert(e.xy);
		//popup = new OpenLayers.Popup("Markers",
        //           new OpenLayers.LonLat(e),
        //           new OpenLayers.Size(200,100),
        //           "H-1234567890<br>実績収集PC",
        //           true);
		//map.addPopup(popup);
		
	});


  </script>
  <a href="http://www16.tok2.com/home/ind/leaflet.html">Leafletを使ったOSMの表示<a/>

 <!--実験用-->
 <!--
    <div id="popup" class="white-popup">
        Dynamically created popup
    </div>

    <script type="text/javascript">
    $(window).load(function(){
        $.magnificPopup.open({
            items: {src: '#popup'},
            type: 'inline', 
            modal: true,
        }, 0);
    });
    </script>    
-->
 <!--実験用-->	

</body>
</html>
<!-- text below generated by geocities.jp -->
</object>
</layer>
</div>
</span>
</style>
</noscript>
</table>
</script>
</applet>
<script language="javascript" src="//bc-geocities.yahoo.co.jp/js/geov2.js"></script>
<script language="javascript">geovisit();</script>